---
# Source: defectdojo/charts/mysql/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: defectdojo-mysql
  namespace: "security-tools"
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: defectdojo
automountServiceAccountToken: true
secrets:
  - name: defectdojo-mysql-specific
