---
# Source: defectdojo/charts/mysql/templates/primary/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: defectdojo-mysql
  namespace: "security-tools"
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: defectdojo
    app.kubernetes.io/component: primary
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: mysql
  selector: 
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: defectdojo
    app.kubernetes.io/component: primary
