---
# Source: defectdojo/templates/secret-redis.yaml
apiVersion: v1
kind: Secret
metadata:
  name: defectdojo-redis-specific
  namespace: security-tools
  labels:
    app.kubernetes.io/name: defectdojo
    app.kubernetes.io/instance: defectdojo
type: Opaque
data:
  redis-password: "dmxBRmM0ZE9rUw=="
