---
# Source: defectdojo/charts/redis/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: defectdojo-redis
  namespace: "security-tools"
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: defectdojo
