---
# Source: defectdojo/charts/redis/templates/headless-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: defectdojo-redis-headless
  namespace: security-tools
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: defectdojo
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: redis
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: defectdojo
