---
# Source: defectdojo/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: defectdojo
  labels:
    app.kubernetes.io/name: defectdojo
    app.kubernetes.io/instance: defectdojo
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: defectdojo-1.6.82
data:
  DD_ADMIN_USER: admin
  DD_ADMIN_MAIL: admin@defectdojo.local
  DD_ADMIN_FIRST_NAME: Admin
  DD_ADMIN_LAST_NAME: User
  DD_ALLOWED_HOSTS: "127.0.0.1,defectdojo-django"
  DD_SITE_URL: http://localhost:8080
  DD_CELERY_BROKER_SCHEME: redis
  DD_CELERY_BROKER_USER: ''
  DD_CELERY_BROKER_HOST: defectdojo-redis-master
  DD_CELERY_BROKER_PORT: '6379'
  DD_CELERY_BROKER_PARAMS: ''
  DD_CELERY_BROKER_PATH: '//'
  DD_CELERY_LOG_LEVEL: INFO
  DD_CELERY_WORKER_POOL_TYPE: solo
  DD_CELERY_WORKER_AUTOSCALE_MIN: ''
  DD_CELERY_WORKER_AUTOSCALE_MAX: ''
  DD_CELERY_WORKER_CONCURRENCY: ''
  DD_CELERY_WORKER_PREFETCH_MULTIPLIER: ''
  DD_DATABASE_ENGINE: django.db.backends.mysql
  DD_DATABASE_HOST: defectdojo-mysql
  DD_DATABASE_PORT: '3306'
  DD_DATABASE_USER: defectdojo
  DD_DATABASE_NAME: defectdojo
  DD_INITIALIZE: 'true'
  DD_UWSGI_ENDPOINT: /run/defectdojo/uwsgi.sock
  DD_UWSGI_HOST: localhost
  DD_UWSGI_PASS: unix:///run/defectdojo/uwsgi.sock
  DD_UWSGI_NUM_OF_PROCESSES: '2'
  DD_UWSGI_NUM_OF_THREADS: '2'
  DD_DJANGO_METRICS_ENABLED: 'true'
  NGINX_METRICS_ENABLED: 'true'
  METRICS_HTTP_AUTH_USER: monitoring
  DD_CSRF_TRUSTED_ORIGINS: "http://127.0.0.1,http://defectdojo-django"
  DD_DEBUG: "true"