---
# Source: defectdojo/templates/secret-mysql.yaml
apiVersion: v1
kind: Secret
metadata:
  name: defectdojo-mysql-specific
  labels:
    app.kubernetes.io/name: defectdojo
    app.kubernetes.io/instance: defectdojo
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: defectdojo-1.6.82
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
type: Opaque
data:
  mysql-root-password: "cTh2QTJReHJMTg=="
  mysql-password: "elhpT1NiMzZJbA=="
  mysql-replication-password: "Uk1RVWhKQTRrOQ=="
