---
# Source: defectdojo/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: defectdojo
  namespace: security-tools
  labels:
    app.kubernetes.io/name: defectdojo
    app.kubernetes.io/instance: defectdojo
type: Opaque
data:
  DD_ADMIN_PASSWORD: "REQtMTMzNy1GVFctZHVtbXlfcDRzcw=="
  DD_SECRET_KEY: "TGpKSXk4S2tja09yTVFDZ1Z0WFlVVExxMGg4UTlqTFN6dW53SnNqOWZLcXVTQnZ3QXVoQWM0QXpIMTN5TUFZNHp4QnZNWldwSXl5U0NTMEVncXhLcDBSMWdReGhmSWg5Z3A3NXBwSjhKRjRhZlJja1pqVU1UTXJIemc0R0Z5dW8="
  DD_CREDENTIAL_AES_256_KEY: "VmR5RzhYeHdka21WOHpxSXhyWGpvekVJeXZhcFVMNm5XRzF4R2JQWjY0WWFRUm5qemwxOVliNndoeUVYeWRBNWRpd0ZtMnpSd2x0bk1TQXNlcDdmTjNPOXdnaFplZDZrWGVad2FJMHA0enVhS3Q3VUU3NnpIZk9lcm55OUs4V1A="
  METRICS_HTTP_AUTH_PASSWORD: "Ujlremx3T0FYdkZMOVVyakE5U1dZa0FrdVdUcVE3M3g="
