---
# Source: defectdojo/templates/sa.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: defectdojo
  namespace: "security-tools"
  labels:
    app.kubernetes.io/name: defectdojo
    app.kubernetes.io/instance: defectdojo
