---
# Source: defectdojo/templates/django-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: defectdojo-django
  namespace: "security-tools"
  labels:
    defectdojo.org/component: django
    app.kubernetes.io/name: defectdojo
    app.kubernetes.io/instance: defectdojo
spec:
  selector:
    defectdojo.org/component: django
    app.kubernetes.io/name: defectdojo
    app.kubernetes.io/instance: defectdojo
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
