---
# Source: defectdojo/templates/celery-worker-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: defectdojo-celery-worker
  labels:
    defectdojo.org/component: celery
    app.kubernetes.io/name: defectdojo
    app.kubernetes.io/instance: defectdojo
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: defectdojo-1.6.82
spec:
  replicas: 1
  selector:
    matchLabels:
      defectdojo.org/component: celery
      app.kubernetes.io/name: defectdojo
      app.kubernetes.io/instance: defectdojo
  template:
    metadata:
      labels:
        defectdojo.org/component: celery
        app.kubernetes.io/name: defectdojo
        app.kubernetes.io/instance: defectdojo
      annotations:
        checksum/config: 15d0a45898c24a25499b006795e97f77e3f07c8abbefdb08a917ff7d2ff26575
        checksum/secret: 0d7833c1fb618686c3c3d6e9c562889e098a0e450fdc41d3d183952f7c2f071b
        checksum/esecret: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
    spec:
      serviceAccountName: defectdojo
      volumes:
      containers:
      - name: celery
        image: "defectdojo/defectdojo-django:2.25.4"
        imagePullPolicy: Always
        securityContext:
          runAsUser: 1001
        command: ['/entrypoint-celery-worker.sh']
        volumeMounts:
        envFrom:
        - configMapRef:
            name: defectdojo
        - secretRef:
            name: defectdojo-extrasecrets
            optional: true
        env:
        - name: DD_CELERY_BROKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: defectdojo-redis-specific
              key: redis-password
        - name: DD_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
                name: defectdojo-mysql-specific
                key: mysql-password
        - name: DD_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: defectdojo
              key: DD_SECRET_KEY
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
