apiVersion: v1
kind: ConfigMap
metadata:
  name: postee-custom-templates
  namespace: "security-tools"
data:
  rego-trivy.rego: "# METADATA\n# title: trivy-operator-custom-defectdojo\n# scope:
    package\npackage postee.trivyoperator.custom.defectdojo  \n\ntitle:=\"-\" #not
    used with webhook\n\nget_month_from_date(timestamp) = month {\n    ts := timestamp\n
    \   t := time.parse_rfc3339_ns(ts)\n    month := time.date(t)[1]\n}\n\nget_month_name_from_date(timestamp)
    = month_name {\n    dict := {\n        1: \"January\",\n        2: \"February\",\n
    \       3: \"March\",\n        4: \"April\",\n        5: \"May\",\n        6:
    \"June\",\n        7: \"July\",\n        8: \"August\",\n        9: \"September\",\n
    \       10: \"October\",\n        11: \"November\",\n        12: \"December\"\n
    \   }\n    month_name := dict[get_month_from_date(timestamp)]\n}\n\nformat_to_dd_date(timeStamp)
    = dd_date {\n    ts := timeStamp\n    t := time.parse_rfc3339_ns(ts)\n    dd_date
    := sprintf(\"%04d-%02d-%02d\", [time.date(t)[0], time.date(t)[1], time.date(t)[2]])\n}\n\nimage_name
    := sprintf(\"%s/%s\", [input.operatorObject.report.registry.server, input.operatorObject.report.artifact.repository])\nimage_version
    := input.operatorObject.report.artifact.tag\nimage_full_name := sprintf(\"%s:%s\",
    [image_name, image_version])\n\n# this following JSON structure's format is dictated
    by how the\n# underlying CURL command is expecting the incoming JSON payload\n#
    to look like.\ndd_data:= {\n  \"defectdojo\": {\n    \"verb\": input.verb,\n    \"scan\":
    input.operatorObject,\n    \"metadata\": {\n      \"active\": true,\n      \"verified\":
    false,\n      \"engagement_name\": sprintf(\"FedRamp Audit - %s\", [get_month_name_from_date(input.operatorObject.metadata.creationTimestamp)]),\n
    \     \"environment\": \"Lab\",\n      \"minimum_severity\": \"Low\",\n      \"product_name\":
    \"k8s-poc\",\n      \"product_type_name\": \"kubernetes_cluster\",\n      \"auto_create_context\":
    true,\n      \"scan_date\": format_to_dd_date(input.operatorObject.metadata.creationTimestamp),\n
    \     \"scan_type\": \"Trivy Operator Scan\",\n      \"test_title\": input.operatorObject.metadata.name,\n
    \     \"service\": image_name,\n      \"version\": image_version,\n      \"group_by\":
    \"component_name\",\n      \"close_old_findings\": false,\n      \"clode_old_findings_product_scope\":
    false,\n      \"deduplication_on_engagement\": true,\n      \"do_not_reactivate\":
    false,\n      \"tags\": [sprintf(\"image=%s\", [image_full_name]), sprintf(\"namespace=%s\",
    [input.operatorObject.metadata.labels[\"trivy-operator.resource.namespace\"]]),
    sprintf(\"name=%s\", [input.operatorObject.metadata.labels[\"trivy-operator.resource.name\"]]),
    sprintf(\"container=%s\", [input.operatorObject.metadata.labels[\"trivy-operator.container.name\"]]),
    sprintf(\"kind=%s\", [input.operatorObject.metadata.labels[\"trivy-operator.resource.kind\"]])]\n
    \   }\n  }\n}\n\nresult:= dd_data"
