---
# Source: postee/templates/postee-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: postee
  labels:
    helm.sh/chart: postee-v2.14.0
    app.kubernetes.io/name: postee
    app.kubernetes.io/instance: postee
    app.kubernetes.io/version: "v2.14.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
    - port: 8445
      targetPort: 8445
      protocol: TCP
      name: http-ssl
  selector:
    app.kubernetes.io/name: postee
    app.kubernetes.io/instance: postee
