---
# Source: postee/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postee
  namespace: security-tools
  labels:
    app.kubernetes.io/name: postee
    app.kubernetes.io/instance: postee
    app.kubernetes.io/version: "v2.14.0"
