---
# Source: postee/templates/postee.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postee
  namespace: security-tools
  labels:
    app.kubernetes.io/name: postee
    app.kubernetes.io/instance: postee
    app.kubernetes.io/version: "v2.14.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postee
      app.kubernetes.io/instance: postee
  serviceName: postee
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postee
        app.kubernetes.io/instance: postee
    spec:
      serviceAccountName: postee
      securityContext: {}
      initContainers:
        - name: setting-db
          image: "busybox:1.34"
          imagePullPolicy: IfNotPresent
          command: ["/bin/chown", "-R", "1099", "/server/database"]
          volumeMounts:
            - name: postee-db
              mountPath: /server/database
        - name: setting-cfg
          image: "busybox:1.34"
          imagePullPolicy: IfNotPresent
          command: ["/bin/cp", "/k8s/cfg.yaml", "/data/cfg.yaml"]
          volumeMounts:
            - name: postee-configmap-vol
              mountPath: /k8s
            - name: postee-config
              mountPath: /data
      containers:
        - name: postee
          securityContext: {}
          image: "aquasec/postee:2.14.0-amd64"
          imagePullPolicy: Always
          env:
            - name: POSTEE_CFG
              value: /data/cfg.yaml
            - name: POSTEE_DEBUG
              value: "not"
            - name: DEFECTDOJO_URL
              valueFrom:
                secretKeyRef:
                  name: postee-dd-env
                  key: url
            - name: DEFECTDOJO_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: postee-dd-env
                  key: token
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
            - name: tls
              containerPort: 8445
              protocol: TCP
          volumeMounts:
            - name: postee-db
              mountPath: /server/database
            - name: postee-config
              mountPath: /data
            - name: postee-rego-template
              mountPath: /server/rego-templates/custom
            - name: postee-filters
              mountPath: /server/rego-filters/custom
            - name: custom-templates
              mountPath: /server/rego-templates/my-custom
            - name: custom-scripts
              mountPath: /server/scripts
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: postee-db
          emptyDir: {}
        - name: postee-config
          emptyDir: {}
        - name: postee-rego-template
          emptyDir: {}
        - name: postee-filters
          emptyDir: {}
        - name: postee-configmap-vol
          configMap:
            name: postee-config
            items:
              - key: cfg.yaml
                path: cfg.yaml
        - name: custom-templates
          configMap:
            name: postee-custom-templates
            items:
              - key: rego-trivy.rego
                path: rego-trivy.rego
        - name: custom-scripts
          configMap:
            name: postee-custom-scripts
            items:
              - key: dd-upload.sh
                path: dd-upload.sh
