---
# Source: defectdojo/charts/mysql/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: defectdojo-mysql
  namespace: "security-tools"
  labels:
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-9.1.8
    app.kubernetes.io/instance: defectdojo
    app.kubernetes.io/managed-by: Helm
  annotations:
automountServiceAccountToken: true
secrets:
  - name: defectdojo-mysql-specific
