---
# Source: trivy-operator/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: trivy-operator
rules:
  - apiGroups:
    - aquasecurity.github.io
    resources:
    - '*'
    verbs:
    - get
    - list
    - update
    - delete
    - patch
    - watch
    - create