---
# Source: trivy-operator/templates/config.yaml
apiVersion: v1
kind: Secret
metadata:
  name: trivy-operator-trivy-config
  namespace: "security-tools"
  labels:
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/version: "0.15.1"
data:
  TRIVY_USERNAME: ""
  TRIVY_PASSWORD: ""