---
# Source: trivy-operator/templates/trivy-server.yaml
apiVersion: v1
kind: Service
metadata:
  name: trivy-service
  namespace: "security-tools"
  labels:
    app.kubernetes.io/name: trivy-server
    app.kubernetes.io/instance: trivy-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: trivy-server
    app.kubernetes.io/instance: trivy-server
  ports:
    - name: trivy-http
      protocol: TCP
      port: 4954
      targetPort: 4954
  sessionAffinity: ClientIP