---
# Source: trivy-operator/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trivy-operator
  namespace: security-tools
  labels:
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/version: "0.15.1"
    app.kubernetes.io/managed-by: k8s-systems_powered-by-helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: trivy-operator
      app.kubernetes.io/instance: trivy-operator
  endpoints:
  - honorLabels: true
    port: metrics
    scheme: http
