---
# Source: trivy-operator/templates/trivy-server.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trivy-server
  namespace: "security-tools"
  labels:
    app.kubernetes.io/name: trivy-server
    app.kubernetes.io/instance: trivy-server
spec:
  podManagementPolicy: "Parallel"
  serviceName: trivy-service
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: trivy-server
      app.kubernetes.io/instance: trivy-server
  template:
    metadata:
      annotations:
        checksum/config: 7fcc66ace3f98462349856795765021e7bf7a0106f28439a9f6dc74257404370
      labels:
        app.kubernetes.io/name: trivy-server
        app.kubernetes.io/instance: trivy-server
    spec:
      serviceAccountName: trivy-operator
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: main
          image: "ghcr.io/aquasecurity/trivy:0.44.1"
          imagePullPolicy: "IfNotPresent"
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
          args:
            - server
          envFrom:
            - configMapRef:
                name: trivy-operator-trivy-config
            - secretRef:
                name: trivy-operator-trivy-config
          ports:
            - name: trivy-http
              containerPort: 4954
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: trivy-http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: trivy-http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - mountPath: /tmp
              name: tmp-data
              readOnly: false
            - mountPath: /home/scanner/.cache
              name: data
              readOnly: false
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 512Mi
      volumes:
        - name: tmp-data
          emptyDir: {}
        - name: data
          emptyDir: {}
