createSecret: true
createRabbitMqSecret: false
createRedisSecret: true
createMysqlSecret: true
createPostgresqlSecret: false

host: 127.0.0.1
database: mysql

admin:
  user: admin
  password: DD-1337-FTW-dummy_p4ss
  firstName: Agent
  lastName: Smith

django:
  ingress:
    enabled: false
  uswgi:
    enable_debug: true

celery:
  broker: redis

mysql:
  enabled: true
  auth:
    username: defectdojo
    password: dummy_p4ss_1337
    database: defectdojo
    rootPassword: r00t_dummy_p4ss_1337_r00t
  primary:
    persistence:
      storageClass: localpv-vip-database
  #mysqlServer: vitess-defectdojo-db

postgresql:
  enabled: false

redis:
  enabled: true
  master:
    persistence:
      enabled: false


rabbitmq:
  enabled: false
  ulimitNofiles: ""
  persistence:
    enabled: false
#
extraConfigs:
  DD_DEBUG: "true"
  DD_CSRF_TRUSTED_ORIGINS: "http://127.0.0.1"
  DD_ALLOWED_HOSTS: "127.0.0.1"

monitoring:
  enabled: true
  # Add the nginx prometheus exporter sidecar
  prometheus:
    enabled: true
    image: nginx/nginx-prometheus-exporter:0.11.0
    imagePullPolicy: IfNotPresent