targetNamespaces: "security-tools"
targetWorkloads: "pod,replicaset,replicationcontroller,statefulset,daemonset,cronjob,job"
managedBy: "k8s-systems_powered-by-helm"

compliance:
  reportType: all

operator:
  scannerReportTTL: 24h
  logDevMode: true
  scanJobsConcurrentLimit: 10
  scanNodeCollectorLimit: 1
  builtInTrivyServer: true
  configAuditScannerEnabled: false
  rbacAssessmentScannerEnabled: false
  infraAssessmentScannerEnabled: false
  clusterComplianceEnabled: false
  sbomGenerationEnabled: false
  exposedSecretScannerEnabled: false
  batchDeleteLimit: 10
  metricsFindingsEnabled: false
  metricsVulnIdEnabled: false
  accessGlobalSecretsAndServiceAccount: false
  #privateRegistryScanSecretsNames: {"app": "dockerconfigjson-harbor"}
  webhookBroadcastURL: http://postee.svc:8082
  webhookBroadcastTimeout: 60s
  webhookSendDeletedReports: true

trivyOperator:
  additionalReportLabels: env=lab,team=core-team
  reportResourceLabels: "team"

serviceMonitor:
  enabled: false

trivy:
  additionalVulnerabilityReportFields: "Description,Links,CVSS,Target,Class,PackagePath,PackageType"
  debug: true
  image:
    tag: 0.44.1
  slow: false
  ignoreUnfixed: true
  #insecureRegistries: {"harbor": "registry.k8s.127-0-0-1.nip.io"}